Update reshaper_config.py
removed unused `from pkg_resources import resource_filename`
This causes an error "AttributeError: 'PosixPath' object has no attribute 'startswith'" on python devcontainer docker container.